# Tensors

A tensor is container, consist of numerical data such float32 or int32, having multidimensions

### Scalar Tensors

Tensors which contain only one digit, and having number of axes are zero

In [2]:
import numpy as np
x = np.array(12);
print('x = ', x)
print('dimesions = ', x.ndim)

x =  12
dimesions =  0


### 1D Tensors

A array of numerical data, is called as vector or *1D tensor*

In [3]:
x = np.array([2, 3, 7, 2, 9])
print('x = ', x)
print('dimesions = ', x.ndim)

x =  [2 3 7 2 9]
dimesions =  1


### 2D Tensors

A array of vectors is matrix or a **2D Tensor**. A matrix has two axes, named as *rows* and *columns*

In [5]:
x = np.array([[2, 3, 4, 5], [4, 3, 6, 5], [8, 2, 1, 4]])
print('x = \n', x)
print('dimesions = ', x.ndim)

x = 
 [[2 3 4 5]
 [4 3 6 5]
 [8 2 1 4]]
dimesions =  2


### 3D Tensors

If we pack 2D tensors in a array, we obtain a **3D Tensor** also called as *cubic tensor* 

In [6]:
x = np.array([[[2, 3, 4, 5], [4, 3, 6, 5], [8, 2, 1, 4]], [[2, 3, 4, 5], [4, 3, 6, 5], [8, 2, 1, 4]]])
print('x = \n', x)
print('dimesions = ', x.ndim)

x = 
 [[[2 3 4 5]
  [4 3 6 5]
  [8 2 1 4]]

 [[2 3 4 5]
  [4 3 6 5]
  [8 2 1 4]]]
dimesions =  3
